workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling/.dockstore.yml

Fixes a problem that breaks the build (see https://github.com/galaxyproject/iwc/runs/2803865520) now that `planemo-ci-action` has been updated to include https://github.com/galaxyproject/planemo-ci-action/pull/19.
Before this fix:
```
$ planemo workflow_lint --fail_level error workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling
Applying linter dockstore... FAIL
.. ERROR: .dockstore.yml workflow entry references absent file /se-wgs-variation.ga-test.yml
Applying linter tests... CHECK
.. CHECK: Tests appear structurally correct for workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling/se-wgs-variation.ga
```
After this fix:
```
(venv) [simleo@neuron:iwc (fix_dockstore)]$ planemo workflow_lint --fail_level error …
```

Fix reference to test file in sars-cov-2-se-illumina-wgs-variant-calling

---

workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling/README.md

to fix the description on [WorkflowHub](https://workflowhub.eu/workflows/112) which is inconsistent ("COVID-19: variation analysis on WGS PE data" for the SE workflow)

Fix title in README for sars-cov-2-se-illumina-wgs-variant-calling

---

workflows/README.md
workflows/gen_crates.py
workflows/requirements.txt

Changes `gen_crates.py` to use the same repository discovery logic as Planemo (uses `planemo` as a dependency). This means that the script can now be simply called without arguments from the `workflows` dir, and it will add RO-Crate metadata to all repo dirs.

Add repository discovery to gen_crates

---

.github/workflows/workflow_test.yml

Updates the GitHub workflow with steps to generate RO-Crate metadata for all the workflows before deployment, using the `gen_crates.py` tool.
The deployment phase will actually be skipped for _this_ PR, since no workflow has changed. I'm not sure what would be the best way to "force" the addition of the RO-Crate files to the repos, since the deploy action updates a repo only for new workflow releases.

Generate RO-Crate metadata before deployment

---

bump_version.py

Updates `bump_version.py` to handle the ["Unreleased" log entry](https://keepachangelog.com/en/1.0.0/#effort).
Additionally, it is now possible to specify a heading-only new log entry by providing an empty log message (`python bump_version.py -m ''`). Rather than actually adding an empty section to the changelog, the indented usage is to avoid having to specify additional changes when making a new release for a workflow whose latest changes are already listed in the `Unreleased` section.
For instance, when bumping the version for:
```markdown
Changelog for SuperWorkflow
- This and that
- First version of SuperWorkflow
```
We want the entry for 0.1.1 to list the currently unreleased changes, and perhaps we don't want to add anything else. This is where `-m ''` comes in handy (the default …

Update bump_version tool

---

workflows/data-fetching/parallel-accession-download/.workflowhub.yml
workflows/gen_crates.py
workflows/requirements.txt
workflows/sars-cov-2-variant-calling/sars-cov-2-consensus-from-variation/.workflowhub.yml
workflows/sars-cov-2-variant-calling/sars-cov-2-ont-artic-variant-calling/.workflowhub.yml
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-variant-calling/.workflowhub.yml
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling/.workflowhub.yml
workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling/.workflowhub.yml
workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/.workflowhub.yml

Extends the `gen_crates` tool with functionality to upload RO-Crates to WorkflowHub.
The tool needed some additional info to perform this action:
* WorkflowHub URL: defaults to https://workflowhub.eu, can be overridden with `--hub-url` (can point to https://dev.workflowhub.eu or http://localhost:3000 for testing)
* WorkflowHub API key for authentication: passed via the `HUB_API_KEY` environment variable (passing this via CLI would not be safe). We should be able to set this from a secret in GitHub Actions
* WorkflowHub team/project name: read from `.workflowhub.yml`, can be overridden with `--hub-project`. Can be omitted in `.workflowhub.yml`, but then `--hub-project` must be specified.
* WorkflowHub workflow name: read from `.workflowhub.yml`. If a workflow with this name is found in the …

RO-Crate upload to WorkflowHub

---

.github/workflows/setup.yml
.github/workflows/test_workflows.yml

Adds two [reusable workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) that implement, respectively, the `setup` and `test` jobs from the main [workflow_test.yml](https://github.com/galaxyproject/iwc/blob/276549c2ee2fcc95aeddd82caf4df980dc72d829/.github/workflows/workflow_test.yml) CI workflow. These workflows are meant to be integrated in the main workflow (tested [here](https://github.com/simleo/iwc/tree/test_reusable_wf)) and in the upcoming [workflow-specific CI workflows](https://github.com/galaxyproject/iwc/pull/74) (tested [here](https://github.com/simleo/sars-cov-2-se-illumina-wgs-variant-calling)).
Note that this PR does _not_ integrate the workflows anywhere: it just adds them to the repo so that they can be called in subsequent PRs.

Reusable CI workflows

---

workflows/computational-chemistry/fragment-based-docking-scoring/CHANGELOG.md
workflows/computational-chemistry/fragment-based-docking-scoring/fragment-based-docking-scoring.ga
workflows/computational-chemistry/gromacs-dctmd/CHANGELOG.md
workflows/computational-chemistry/gromacs-dctmd/gromacs-dctmd.ga
workflows/computational-chemistry/gromacs-mmgbsa/CHANGELOG.md
workflows/computational-chemistry/gromacs-mmgbsa/gromacs-mmgbsa.ga
workflows/computational-chemistry/protein-ligand-complex-parameterization/CHANGELOG.md
workflows/computational-chemistry/protein-ligand-complex-parameterization/protein-ligand-complex-parameterization.ga
workflows/data-fetching/parallel-accession-download/CHANGELOG.md
workflows/data-fetching/parallel-accession-download/parallel-accession-download.ga
workflows/gen_crates.py
workflows/sars-cov-2-variant-calling/sars-cov-2-consensus-from-variation/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-consensus-from-variation/consensus-from-variation.ga
workflows/sars-cov-2-variant-calling/sars-cov-2-ont-artic-variant-calling/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-ont-artic-variant-calling/ont-artic-variation.ga
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis/pe-wgs-ivar-analysis.ga
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-variant-calling/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-variant-calling/pe-artic-variation.ga
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling/pe-wgs-variation.ga
workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-se-illumina-wgs-variant-calling/se-wgs-variation.ga
workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/variation-reporting.ga
workflows/wftest.yml

Resolves #71.
The script that generates RO-Crate metadata files now also places a GitHub workflow that tests the scientific workflow under `.github/workflows`, allowing each deployed repository to have its own GitHub Actions history reflecting the status of its specific workflow. The GitHub workflow is set to run on a daily schedule and it's also configured to enable manual triggering; I've tested it on a fork of `iwc-workflows/sars-cov-2-pe-illumina-artic-variant-calling`, see https://github.com/simleo/sars-cov-2-pe-illumina-artic-variant-calling/actions.

Workflow-specific CI workflows

---

workflows/data-fetching/parallel-accession-download/CHANGELOG.md
workflows/data-fetching/parallel-accession-download/parallel-accession-download.ga

Hello! This is an automated update of the following workflow: **workflows/data-fetching/parallel-accession-download**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/2.11.0+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/2.11.0+galaxy1`
The workflow release number has been updated from 0.1.2 to 0.1.3.

Updating workflows/data-fetching/parallel-accession-download from 0.1.2 to 0.1.3

---

workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/variation-reporting.ga

Hello! This is an automated update of the following workflow: **workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/snpsift/snpSift_filter/4.3+t.galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/snpsift/snpSift_filter/4.3.0`
* `toolshed.g2.bx.psu.edu/repos/iuc/snpsift/snpSift_extractFields/4.3+t.galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/snpsift/snpSift_extractFields/4.3.0`
* `toolshed.g2.bx.psu.edu/repos/nml/collapse_collections/collapse_dataset/4.2` …

Updating workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting from 0.1.2 to 0.1.3

---

workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling/pe-wgs-variation.ga

Hello! This is an automated update of the following workflow: **workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.20.1+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.23.2+galaxy0`
* `toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa_mem/0.7.17.1` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa_mem/0.7.17.2`
* `toolshed.g2.bx.psu.edu/repos/iuc/samtools_view/samtools_view/1.9+galaxy2` should be updated to …

Updating workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-wgs-variant-calling from 0.2.2 to 0.2.3

---

.github/workflows/enable_ci_workflows.yml
workflows/enable_ci_workflows.py

Deployed (scientific) workflows in [iwc-workflows](https://github.com/iwc-workflows) are automatically set up with a CI workflow that runs tests once per day. Since those repositories get updated only when there's a new release, however, they often run into the 60-day limit beyond which periodic CI workflows get automatically disabled if there's no repository activity.
This PR adds a CI workflow to this repository that checks every day for disabled CI workflows among the iwc-workflows repositories and re-enables them if they were deactivated due to repository inactivity.

CI workflow to re-enable iwc-workflows CI workflows

---

workflows/VGP-assembly-v2/VGP-meryldb-creation-trio/CHANGELOG.md

autoupdate failed because one workflow does not have changelog.
We should have in the CI something like:
```
for f in $(find . -name "*.ga"); do
dir=$(dirname $f)
if [ ! -e "$dir/README.md" ]; then
echo "$dir has no README"
fi
if [ ! -e "$dir/CHANGELOG.md" ]; then
echo "$dir has no CHANGELOG"
fi
if [ ! -e "$dir/.dockstore.yml" ]; then
echo "$dir has no dockstore"
fi
if [ ! -e "$dir/.workflowhub.yml" ]; then
echo "$dir has no workflowhub"
fi
done
```

add missing CHANGELOG

---

workflows/epigenetics/chipseq-sr/CHANGELOG.md
workflows/epigenetics/chipseq-sr/chipseq-sr-tests.yml
workflows/epigenetics/chipseq-sr/chipseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy1`
* `toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8`

Updating workflows/epigenetics/chipseq-sr from 0.1 to 0.2

---

workflows/epigenetics/chipseq-pe/CHANGELOG.md
workflows/epigenetics/chipseq-pe/chipseq-pe-tests.yml
workflows/epigenetics/chipseq-pe/chipseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy1`
* `toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8`

Updating workflows/epigenetics/chipseq-pe from 0.1 to 0.2

---

workflows/epigenetics/cutandrun/CHANGELOG.md
workflows/epigenetics/cutandrun/cutandrun-tests.yml
workflows/epigenetics/cutandrun/cutandrun.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/cutandrun**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy1`
* `toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8`
* `toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.30.0+galaxy2` should be updated to …

Updating workflows/epigenetics/cutandrun from 0.1 to 0.2

---

workflows/epigenetics/atacseq/CHANGELOG.md
workflows/epigenetics/atacseq/atacseq-tests.yml
workflows/epigenetics/atacseq/atacseq.ga

* `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy1`
* `toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.30.0+galaxy2` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bamtobed/2.30.0`
* `toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_slopbed/2.30.0+galaxy1` should be updated to …

Updating workflows/epigenetics/atacseq from 0.1 to 0.2

---

workflows/transcriptomics/rnaseq-pe/CHANGELOG.md
workflows/transcriptomics/rnaseq-pe/rnaseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a`

Updating workflows/transcriptomics/rnaseq-pe from 0.1 to 0.2

---

workflows/transcriptomics/rnaseq-sr/CHANGELOG.md
workflows/transcriptomics/rnaseq-sr/rnaseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.7.8a`

Updating workflows/transcriptomics/rnaseq-sr from 0.1 to 0.2

---

workflows/epigenetics/chipseq-sr/CHANGELOG.md
workflows/epigenetics/chipseq-sr/chipseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

Updating workflows/epigenetics/chipseq-sr from 0.2 to 0.3

---

workflows/epigenetics/chipseq-pe/CHANGELOG.md
workflows/epigenetics/chipseq-pe/chipseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

Updating workflows/epigenetics/chipseq-pe from 0.2 to 0.3

---

workflows/epigenetics/cutandrun/CHANGELOG.md
workflows/epigenetics/cutandrun/cutandrun.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/cutandrun**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.3` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.2`

Updating workflows/epigenetics/cutandrun from 0.2 to 0.3

---

workflows/transcriptomics/rnaseq-sr/CHANGELOG.md
workflows/transcriptomics/rnaseq-sr/rnaseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

Updating workflows/transcriptomics/rnaseq-sr from 0.2 to 0.3

---

workflows/transcriptomics/rnaseq-pe/CHANGELOG.md
workflows/transcriptomics/rnaseq-pe/rnaseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.

Updating workflows/transcriptomics/rnaseq-pe from 0.2 to 0.3

---

workflows/epigenetics/atacseq/CHANGELOG.md
workflows/epigenetics/atacseq/atacseq.ga

* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.3` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.2`

Updating workflows/epigenetics/atacseq from 0.2 to 0.3

---

workflows/transcriptomics/rnaseq-sr/CHANGELOG.md
workflows/transcriptomics/rnaseq-sr/rnaseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.5.1+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.5.2+galaxy1`

Updating workflows/transcriptomics/rnaseq-sr from 0.3 to 0.4

---

workflows/transcriptomics/rnaseq-pe/CHANGELOG.md
workflows/transcriptomics/rnaseq-pe/rnaseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/transcriptomics/rnaseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.5.1+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.5.2+galaxy1`

Updating workflows/transcriptomics/rnaseq-pe from 0.3 to 0.4

---

workflows/epigenetics/atacseq/CHANGELOG.md
workflows/epigenetics/atacseq/atacseq.ga

* `toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.5.1+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/bamtools_filter/bamFilter/2.5.2+galaxy1`
* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.3` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.2`

Updating workflows/epigenetics/atacseq from 0.3 to 0.4

---

workflows/computational-chemistry/fragment-based-docking-scoring/CHANGELOG.md
workflows/computational-chemistry/fragment-based-docking-scoring/fragment-based-docking-scoring.ga

I'm not sure where those revision numbers are coming from, they are not to be found in the tool shed or test tool shed. This prevents repo installation with `planemo test`

Fix changeset revisions in fragment-based-docking-scoring workflow

---

workflows/epigenetics/chipseq-sr/.dockstore.yml
workflows/epigenetics/chipseq-sr/CHANGELOG.md
workflows/epigenetics/chipseq-sr/README.md
workflows/epigenetics/chipseq-sr/chipseq-sr-tests.yml
workflows/epigenetics/chipseq-sr/chipseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.4+galaxy0`

Updating workflows/epigenetics/chipseq-sr from 0.3 to 0.4

---

workflows/epigenetics/chipseq-pe/.dockstore.yml
workflows/epigenetics/chipseq-pe/CHANGELOG.md
workflows/epigenetics/chipseq-pe/README.md
workflows/epigenetics/chipseq-pe/chipseq-pe-tests.yml
workflows/epigenetics/chipseq-pe/chipseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.0+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.4+galaxy0`

Updating workflows/epigenetics/chipseq-pe from 0.3 to 0.4

---

workflows/epigenetics/cutandrun/CHANGELOG.md
workflows/epigenetics/cutandrun/README.md
workflows/epigenetics/cutandrun/cutandrun-tests.yml
workflows/epigenetics/cutandrun/cutandrun.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/cutandrun**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.3` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.3`

Updating workflows/epigenetics/cutandrun from 0.3 to 0.4

---

workflows/epigenetics/hic-hicup-cooler/.dockstore.yml
workflows/epigenetics/hic-hicup-cooler/CHANGELOG.md
workflows/epigenetics/hic-hicup-cooler/README.md
workflows/epigenetics/hic-hicup-cooler/chic_fastq_to_cool_hicup_cooler-tests.yml
workflows/epigenetics/hic-hicup-cooler/chic_fastq_to_cool_hicup_cooler.ga
workflows/epigenetics/hic-hicup-cooler/hic_fastq_to_cool_hicup_cooler-tests.yml
workflows/epigenetics/hic-hicup-cooler/hic_fastq_to_cool_hicup_cooler.ga
workflows/epigenetics/hic-hicup-cooler/hic_fastq_to_pairs_hicup-tests.yml
workflows/epigenetics/hic-hicup-cooler/hic_fastq_to_pairs_hicup.ga
workflows/epigenetics/hic-hicup-cooler/hic_juicermediumtabix_to_cool_cooler.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/hic-hicup-cooler**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.7+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.8+galaxy0`
* `toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.7+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.8+galaxy0`

Updating workflows/epigenetics/hic-hicup-cooler from 0.1 to 0.2

---

workflows/data-fetching/parallel-accession-download/CHANGELOG.md
workflows/data-fetching/parallel-accession-download/parallel-accession-download.ga

Hello! This is an automated update of the following workflow: **workflows/data-fetching/parallel-accession-download**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.5+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.5+galaxy1`
The workflow release number has been updated from 0.1.4 to 0.1.5.

Updating workflows/data-fetching/parallel-accession-download from 0.1.4 to 0.1.5

---

workflows/transcriptomics/rnaseq-pe/.dockstore.yml
workflows/transcriptomics/rnaseq-pe/CHANGELOG.md
workflows/transcriptomics/rnaseq-pe/rnaseq-pe.ga
workflows/transcriptomics/rnaseq-sr/.dockstore.yml
workflows/transcriptomics/rnaseq-sr/CHANGELOG.md
workflows/transcriptomics/rnaseq-sr/rnaseq-sr.ga

This is to be able to generate DOI.

RNA-seq add author in dockstore file

---

workflows/epigenetics/average-bigwig-between-replicates/CHANGELOG.md
workflows/epigenetics/average-bigwig-between-replicates/average-bigwig-between-replicates.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/average-bigwig-between-replicates**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.2+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.4+galaxy0`

Updating workflows/epigenetics/average-bigwig-between-replicates from 0.1 to 0.2

---

workflows/epigenetics/consensus-peaks/CHANGELOG.md
workflows/epigenetics/consensus-peaks/consensus-peaks-chip-sr.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/consensus-peaks**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.2+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.4+galaxy0`
* `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.2+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_a …

Updating workflows/epigenetics/consensus-peaks from 0.1 to 0.2

---

workflows/epigenetics/atacseq/CHANGELOG.md
workflows/epigenetics/atacseq/atacseq.ga

* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.4` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.3`
* `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.2+galaxy0` should be updated to `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.4+galaxy0`
The workflow release number …

Updating workflows/epigenetics/atacseq from 0.5.1 to 0.5.2

---

workflows/data-fetching/parallel-accession-download/CHANGELOG.md
workflows/data-fetching/parallel-accession-download/parallel-accession-download.ga

Hello! This is an automated update of the following workflow: **workflows/data-fetching/parallel-accession-download**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.5+galaxy1` should be updated to `toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fasterq_dump/3.0.5+galaxy3`
The workflow release number has been updated from 0.1.5 to 0.1.6.

Updating workflows/data-fetching/parallel-accession-download from 0.1.5 to 0.1.6

---

workflows/requirements.txt

With Python 3.10 or newer, [PyYAML 5.4 fails to install](https://github.com/yaml/pyyaml/issues/724) due to a problem with Cython. This is not affecting the CI now since the github workflows are using Python 3.7, but it will if the Python version is bumped in the future (also, it affects anyone who wants to install locally with a recent Python version).

Bump pyyaml version

---

workflows/epigenetics/chipseq-sr/CHANGELOG.md
workflows/epigenetics/chipseq-sr/chipseq-sr.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-sr**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
The workflow release number has been updated from 0.4 to 0.5.

Updating workflows/epigenetics/chipseq-sr from 0.4 to 0.5

---

workflows/epigenetics/chipseq-pe/CHANGELOG.md
workflows/epigenetics/chipseq-pe/chipseq-pe.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/chipseq-pe**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
The workflow release number has been updated from 0.4 to 0.5.

Updating workflows/epigenetics/chipseq-pe from 0.4 to 0.5

---

workflows/epigenetics/consensus-peaks/CHANGELOG.md
workflows/epigenetics/consensus-peaks/consensus-peaks-chip-sr.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/consensus-peaks**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_bigwig_average/deeptools_bigwig_average/3.5.2+galaxy0` …

Updating workflows/epigenetics/consensus-peaks from 0.2 to 0.3

---

workflows/epigenetics/cutandrun/CHANGELOG.md
workflows/epigenetics/cutandrun/cutandrun.ga

Hello! This is an automated update of the following workflow: **workflows/epigenetics/cutandrun**. I created this PR because I think one or more of the component tools are out of date, i.e. there is a newer version available on the ToolShed.
* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.4` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.3`
The workflow release number has been updated from 0.4 to 0.5.

Updating workflows/epigenetics/cutandrun from 0.4 to 0.5

---

workflows/epigenetics/atacseq/CHANGELOG.md
workflows/epigenetics/atacseq/atacseq.ga

* `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.4` should be updated to `toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.3`
The workflow release number has been updated from 0.6 to 0.7.

Updating workflows/epigenetics/atacseq from 0.6 to 0.7

---

workflows/proteomics/openms-metaprosip/metaprosip.ga

https://github.com/galaxyproject/iwc/actions/runs/6208009347/job/16853948282 failed with
`Must set a release version in workflow file
'/home/runner/work/iwc/iwc/workflows/proteomics/openms-metaprosip/metaprosip.ga'`

MetaProSIP: add release

---

.github/workflows/workflow_test.yml

See https://github.com/mvdbeek/iwc/pull/5#issuecomment-1798717986 and https://github.com/mvdbeek/iwc/actions/runs/6785381095?pr=5 for an example

Create markdown summary, post back as comment if test failed

---

workflows/VGP-assembly-v2/Assembly-Hifi-HiC-phasing-VGP4/Assembly-Hifi-HiC-phasing-VGP4.ga
workflows/VGP-assembly-v2/Assembly-Hifi-HiC-phasing-VGP4/CHANGELOG.md
workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/CHANGELOG.md
workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/kmer-profiling-hifi-VGP1.ga

Adds tag filtering to wf4 to automatically select necessary genomescope and meryl outputs of wf1

added tag filtering for wf4. rearranged input ordering for wf1 and wf4

---

.github/workflows/comment_on_pr.yml
.github/workflows/workflow_test.yml

This is highly inspired from [this post](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
Contrarily to current code it works for PR from forks.
I deployed it on my fork and the issue I see is that when the PR workflow does not generate a combined test then the action Comment on the pull request fails because there is no artifact. See https://github.com/lldelisle/iwc/actions/runs/7492377134/job/20395726430
But I don't know how to introduce a if within the script to prevent filtering artifact if it is empty.

Comment on PR with result of workflow test

---

workflows/bacterial_genomics/bacterial_genome_annotation/CHANGELOG.md
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation.ga

Hello 
There is an error in `.ga` file with `81c11f4_2023_12_04` PlasmidFinder database.
I changed it to `plasmidfinder_81c11f4_2023_12_04`
Thanks!

Updating workflows/bacterial_genomics/bacterial_genome_annotation from 1.1.1 to 1.1.2

---

workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/Assembly-decontamination-VGP9-tests.yml
workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/Assembly-decontamination-VGP9.ga
workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/CHANGELOG.md

- Regex for lower and upper case changes now only apply to the sequences. Now works with any type of scaffold name, not only the ones output of VGP8.
- Reduce the number of steps in the workflow.

VGP 9 - Simplify workflow and make it more robust

---

workflows/bacterial_genomics/amr_gene_detection/CHANGELOG.md
workflows/bacterial_genomics/amr_gene_detection/amr_gene_detection.ga

Change percent identity threshold for Resfinder blast results in StarAMR from 98.0% to 90.0% (the filter is too strict!)
Thanks :smiley:

Updating workflows/bacterial_genomics/amr_gene_detection from 1.1.1 to 1.1.2

---

workflows/scRNAseq/fastq-to-matrix-10x/CHANGELOG.md
workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-cellplex-tests.yml
workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-cellplex.ga
workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-v3-tests.yml
workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-v3.ga

I did it manually because the CI autoupdate was not able to autoupdate them.
I also incorporated the changes in test syntax identified in #530

Upgrade scRNA-seq workflows from 0.4 to 0.5

---

workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation-tests.yml

I fixed the test for several outputs identified in https://github.com/galaxyproject/iwc/pull/530.
Thanks 😃

Updating workflows/bacterial_genomics/bacterial_genome_annotation 

---

workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-variant-calling/CHANGELOG.md
workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-variant-calling/pe-artic-variation.ga

These are just the minimal tool updates to make the WF executable on .org without issues.
Other tool updates suggested in #389 I would like to test more carefully first, especially the ivar update to version 1.4.3.
The new version of qualimap (v2.3) suggested there seems to produce less nicely formatted, otherwise identical output than the current version so should likely be avoided permanently.

Tool updates (no expected functional changes) to PE ARTIC WF

---

workflows/bacterial_genomics/bacterial_genome_annotation/CHANGELOG.md
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation-tests.yml
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation.ga

Hello, some tools have been updated (close https://github.com/galaxyproject/iwc/pull/540):
- ToolDistillator `0.9+galaxy0` to `0.9.1+galaxy0`
--> A test had to be corrected
Thanks 😃

Updating workflows/bacterial_genomics/bacterial_genome_annotation from 1.1.4 to 1.1.5

---

workflows/bacterial_genomics/amr_gene_detection/CHANGELOG.md
workflows/bacterial_genomics/amr_gene_detection/amr_gene_detection-tests.yml
workflows/bacterial_genomics/amr_gene_detection/amr_gene_detection.ga
workflows/bacterial_genomics/bacterial_genome_annotation/CHANGELOG.md
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation.ga

Hello, some tools have been updated (close https://github.com/galaxyproject/iwc/pull/539):
- ToolDistillator `0.9+galaxy0` to `0.9.1+galaxy0`
--> A test had to be corrected
Thanks 😃

Updating workflows/bacterial_genomics/amr_gene_detection from 1.1.2 to 1.1.3

---

workflows/bacterial_genomics/amr_gene_detection/CHANGELOG.md
workflows/bacterial_genomics/amr_gene_detection/amr_gene_detection-tests.yml
workflows/bacterial_genomics/amr_gene_detection/amr_gene_detection.ga

Changed input parameters to select databases in WFs. Use "`Attempt restriction based on connections`" instead of "`Provide list of suggested values`".
With that, we don't need to give a list of databases which may or **may not** be present in all `usegalaxy.*` instances.
Thanks :smiley:

Updating workflows/bacterial_genomics/amr_gene_detection from 1.1.3 to 1.1.4

---

workflows/bacterial_genomics/bacterial_genome_annotation/CHANGELOG.md
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation.ga

Changed input parameters to select databases in WFs. Use "`Attempt restriction based on connections`" instead of "`Provide list of suggested values`".
With that, we don't need to give a list of databases which may or **may not** be present in all `usegalaxy.*` instances.
Thanks :smiley:

 Updating workflows/bacterial_genomics/bacterial_genome_annotation from 1.1.5 to 1.1.6

---

workflows/genome-assembly/quality-and-contamination-control/CHANGELOG.md
workflows/genome-assembly/quality-and-contamination-control/quality_and_contamination_control.ga

Changed input parameters to select databases in WFs. Use "`Attempt restriction based on connections`" instead of "`Provide list of suggested values`".
With that, we don't need to give a list of databases which may or **may not** be present in all `usegalaxy.*` instances.
Thanks :smiley:

Updating workflows/genome-assembly/quality-and-contamination-control from 1.1.3 to 1.1.4

---

website/app.vue
website/components/WorkflowList.vue

Setting `h-screen` on the workflow list caused the pages overall size to be the screen height + the header height, causing two scroll bars to appear.
This PR moves the height definition to the app container and uses the dynamic viewport height instead of the viewport height, to avoid height issues in browsers with dynamic ui elements.

Fix page scrolls despite children scrolling

---

.github/workflows/gh-page-build.yml

TODO: work out support for either baseUrl, set on the fly?  Maybe yagni.

Unset nuxt base path prefix to support iwc.galaxyproject.org

---

.github/workflows/gh-page-preview.yml

Limited trigger to changes to `/website/` for now, but we could use this down the road for showing pages for previewing updated workflow artifacts, etc.

Add gh-pages preview builder

---

website/plugins/colorMode.ts

If someone happened to visit iwc.galaxyproject.org with dark mode enabled prior to us swapping to a galaxy-themed light mode by default, the browser could get stuck in dark mode due to the way nuxt stores a key in local storage without unsetting it.  This is a workaround that unsticks the stuck mode.
FOR REVIEWERS:

Fix stuck colormode in website

---

.github/workflows/gh-page-preview.yml
.gitignore
scripts/create_mermaid.py
scripts/workflow_manifest.py
website/components/MarkdownRenderer.vue
website/models/workflow.ts
website/package.json
website/pages/workflow/MarkdownRenderer.vue
website/pages/workflow/[id].vue

These are pretty cool.
I guess some possible next steps might be

First pass at generating mermaid diagrams for all workflows

---

workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/CHANGELOG.md
workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/kmer-profiling-hifi-VGP1.ga
workflows/VGP-assembly-v2/kmer-profiling-hifi-trio-VGP2/CHANGELOG.md
workflows/VGP-assembly-v2/kmer-profiling-hifi-trio-VGP2/kmer-profiling-hifi-trio-VGP2.ga

VGP 1 and 2 - update meryl to the galaxy7 wrapper

---

workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/CHANGELOG.md
workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/kmer-profiling-hifi-VGP1-tests.yml
workflows/VGP-assembly-v2/kmer-profiling-hifi-VGP1/kmer-profiling-hifi-VGP1.ga

Add annotation for vgp1 kmer profiling workflow

---

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md
workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/README.md
workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8-tests.yml
workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga

VGP 8 - Update to 1.0 : replace "filter and merge" tool to bwamem2 -sp option and other improvements

---

website/pages/workflow/[id].vue

Folks who have already selected one of these will have the selection persisted, as expected.
Resolves #700 
FOR REVIEWERS:

Reorder instance selection list to have test/local last.  

---

requirements.txt
scripts/workflow_manifest.py

Now we use git's timestamp instead of mtime which is less reliable.
FOR REVIEWERS:

Update workflow 'updated' timestamp retrieval method

---

website/pages/workflow/[id].vue

Add trsID to workflow page, dump UUID

---

workflows/amplicon-mgnify/mgnify-amplicon-pipeline-v5-complete/CHANGELOG.md
workflows/amplicon-mgnify/mgnify-amplicon-pipeline-v5-complete/mgnify-amplicon-pipeline-v5-complete.ga
workflows/amplicon-mgnify/mgnify-amplicon-pipeline-v5-quality-control-paired-end/CHANGELOG.md
workflows/amplicon-mgnify/mgnify-amplicon-pipeline-v5-quality-control-paired-end/mgnify-amplicon-pipeline-v5-quality-control-paired-end.ga

FOR REVIEWERS:
`toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.0+galaxy3` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.0+galaxy4` in the Paired end sub-WF and in the complete WF.

Updating workflows/amplicon-mgnify/mgnify-amplicon-pipeline-v5-complete from 0.1 to 0.2

---

website/components/GalaxyInstanceSelector.vue
website/package-lock.json
website/package.json
website/pages/workflow/[id].vue

Presents the default list of instances but now also allows custom entry, which is persisted in localstorage.
Also adds the rest of usegalaxy.* servers - usegalaxy.fr, usegalaxy.org.au to the default instances list.
FOR REVIEWERS:

Overhaul Galaxy Instance Selector, add support for usegalay.org.au (and others?)

---

workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/CHANGELOG.md
workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/hi-c-map-for-assembly-manual-curation.ga

- `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_replace_in_line/9.3+galaxy1` was updated to `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_replace_in_line/9.5+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat/9.3+galaxy1` was updated to `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat/9.5+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/4.9+galaxy1` was updated to `toolshed.g2.bx.psu.edu/repos/lparsons/cutadapt/cutadapt/5.0+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.28+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/2.28+galaxy1`
- `toolshed.g2.bx.psu.edu/repos/bgruening/gfastats/gfastats/1.3.9+galaxy2` was updated to …

Update hi c contact map for assembly manual curation

---

workflows/genome-assembly/quality-and-contamination-control/CHANGELOG.md
workflows/genome-assembly/quality-and-contamination-control/README.md
workflows/genome-assembly/quality-and-contamination-control/quality_and_contamination_control-tests.yml
workflows/genome-assembly/quality-and-contamination-control/quality_and_contamination_control.ga

Hello, 
This code (close #678  ):
- Changes tools version: 
- `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.0+galaxy3` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.0+galaxy4`
- `toolshed.g2.bx.psu.edu/repos/iuc/bracken/est_abundance/3.0+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/bracken/est_abundance/3.1+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/recentrifuge/recentrifuge/1.15.0+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/recentrifuge/recentrifuge/1.16.0+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator/tooldistillator/0.9.1+galaxy1` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator/tooldistillator/0.9.2+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator_summarize/tooldistillator_summarize/0.9.1+ga …

Updating workflows/genome-assembly/quality-and-contamination-control from 1.1.6 to 1.1.7

---

website/app.config.ts
website/components/IWCHeader.vue
website/nuxt.config.ts
website/pages/workflow/[id].vue

Addresses issue [#805](https://github.com/galaxyproject/iwc/issues/805)
FOR REVIEWERS:

Accessibility score improvements: adding Title header element to Home Page

---

workflows/bacterial_genomics/bacterial_genome_annotation/CHANGELOG.md
workflows/bacterial_genomics/bacterial_genome_annotation/README.md
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation-tests.yml
workflows/bacterial_genomics/bacterial_genome_annotation/bacterial_genome_annotation.ga

Hello, 
This code (close #795 ):
- Changes Bakta version: `toolshed.g2.bx.psu.edu/repos/iuc/bakta/bakta/1.9.4+galaxy0` to `toolshed.g2.bx.psu.edu/repos/iuc/bakta/bakta/1.9.4+galaxy1`
- Changes the ToolDistillator wrapper version: 
- `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator/tooldistillator/0.9.1+galaxy1`  to `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator/tooldistillator/0.9.2+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator_summarize/tooldistillator_summarize/0.9.1+galaxy1` to `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator_summarize/tooldistillator_summarize/0.9.2+galaxy0`
- Changes the output name/tag of Tooldistillator to `tooldistillator_[results|summarize]_annotation`
- Fixes syntax and parameter errors
This workflow uses databases available on …

Updating workflows/bacterial_genomics/bacterial_genome_annotation from 1.1.7 to 1.1.8

---

workflows/amplicon/amplicon-mgnify/mgnify-amplicon-pipeline-v5-complete/CHANGELOG.md
workflows/amplicon/amplicon-mgnify/mgnify-amplicon-pipeline-v5-complete/mgnify-amplicon-pipeline-v5-complete.ga
workflows/amplicon/amplicon-mgnify/mgnify-amplicon-pipeline-v5-quality-control-paired-end/CHANGELOG.md
workflows/amplicon/amplicon-mgnify/mgnify-amplicon-pipeline-v5-quality-control-paired-end/mgnify-amplicon-pipeline-v5-quality-control-paired-end.ga

FOR REVIEWERS:
**Updates**:
- `toolshed.g2.bx.psu.edu/repos/iuc/fastq_dl/fastq_dl/3.0.0+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/fastq_dl/fastq_dl/3.0.1+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_awk_tool/9.3+galaxy1` was updated to `toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_awk_tool/9.5+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.27+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/multiqc/multiqc/1.27+galaxy3`
- `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.0+galaxy4` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.1+galaxy0`
- `CONVERTER_gz_to_uncompressed` output format was updated to `fastqsanger`
- `CONVERTER_uncompressed_to_gz` output format was updated to …

Update MGnify WFs

---

workflows/virology/influenza-isolates-consensus-and-subtyping/.dockstore.yml
workflows/virology/influenza-isolates-consensus-and-subtyping/CHANGELOG.md
workflows/virology/influenza-isolates-consensus-and-subtyping/README.md
workflows/virology/influenza-isolates-consensus-and-subtyping/influenza-consensus-and-subtyping-test.yml
workflows/virology/influenza-isolates-consensus-and-subtyping/influenza-consensus-and-subtyping.ga

Release v0.2 of influenza workflow

---

website/pages/about.vue
website/pages/index.vue
website/pages/workflow/[id].vue
website/public/category-descriptions/data-fetching.md
website/public/category-descriptions/genome-annotation.md
website/public/category-descriptions/microbiome.md
website/public/category-descriptions/transcriptomics.md

Following our discussions, we're standardizing terminology by using 'workflow' instead of 'pipeline' throughout most of the platform. The tagline "Discover and run vetted analysis pipelines on Galaxy" will remain unchanged since it still makes sense, but we'll refer to specific items as workflows everywhere else.

Standardize terminology to 'workflow's

---

workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/CHANGELOG.md
workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/README.md
workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/hi-c-map-for-assembly-manual-curation-tests.yml
workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/hi-c-map-for-assembly-manual-curation.ga

VGP Precuration - add coverage gaps and MAPQ filtering

---

workflows/genome-assembly/quality-and-contamination-control/CHANGELOG.md
workflows/genome-assembly/quality-and-contamination-control/README.md
workflows/genome-assembly/quality-and-contamination-control/quality_and_contamination_control.ga

Hello, 
This code (close #894  ):
- Changes tools version: 
- `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.24.1+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/fastp/fastp/0.26.0+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator/tooldistillator/0.9.2+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator/tooldistillator/0.9.3+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator_summarize/tooldistillator_summarize/0.9.2+galaxy0` was updated to `toolshed.g2.bx.psu.edu/repos/iuc/tooldistillator_summarize/tooldistillator_summarize/0.9.3+galaxy0`
- Changes datatype output (`fastqsanger.gz`) in Zip collection: Fastp no longer accepts `fastq.gz` as input file
This workflow uses databases available on http://datacache.galaxyproject.org/.
Thanks …

Updating workflows/genome-assembly/quality-and-contamination-control from 1.1.8 to 1.1.9

---

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md
workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8-tests.yml
workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga

VGP8 - Release 3.0 with duplicates removal 
