README.md
@jennaj  and I put together a first pass of a mission statement and readme...
feedback welcome!
=> Mission statement

workflows/sars-cov-2-variant-calling/se-illumina-wgs/se-wgs-variation-test.yml
date is different than yesterday 😆
=> Increase lines diff for SE workflow

.github/workflows/ci.yaml, .github/workflows/slash.yaml, .github/workflows/workflow_test.yml
so we can test different galaxy branches / test workflows on a schedule
=> Add run-all-workflow-tests slash command

workflows/gen_crates.py, workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis/.workflowhub.yml
Adds the ability to upload workflows to LifeMonitor to the `gen_crates.py` tool.
=> gen_crates.py: upload to LifeMonitor

bump_version.py, workflows/computational-chemistry/fragment-based-docking-scoring/CHANGELOG.md, workflows/computational-chemistry/fragment-based-docking-scoring/fragment-based-docking-scoring.ga, workflows/computational-chemistry/gromacs-dctmd/CHANGELOG.md, workflows/computational-chemistry/gromacs-dctmd/gromacs-dctmd.ga, workflows/computational-chemistry/gromacs-mmgbsa/CHANGELOG.md, workflows/computational-chemistry/gromacs-mmgbsa/gromacs-mmgbsa.ga, workflows/computational-chemistry/protein-ligand-complex-parameterization/CHANGELOG.md, workflows/computational-chemistry/protein-ligand-complex-parameterization/protein-ligand-complex-parameterization.ga, workflows/gen_crates.py, workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis/CHANGELOG.md, workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-ivar-analysis/pe-wgs-ivar-analysis.ga
E.g., `"identifier": "0000-0002-0621-6705"` to `"identifier": "https://orcid.org/0000-0002-0621-6705"`
=> Changed creator ORCID to full URI where needed

workflows/README.md
=> Update README.md 

workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/CHANGELOG.md, workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/README.md, workflows/sars-cov-2-variant-calling/sars-cov-2-variation-reporting/variation-reporting.ga
Version 2.0 of column_maker lets us do this.
=> Simplify computations in reporting WF

workflows/README.md
Following #120 
Inputs are welcome
=> improve README in workflows

.github/workflows/ci.yaml, .github/workflows/enable_ci_workflows.yml, .github/workflows/setup.yml, .github/workflows/slash.yaml, .github/workflows/test_workflows.yml, .github/workflows/usegalaxy-star-installation.yml, .github/workflows/workflow_test.yml
=> Workflow GitHub update

.github/workflows/ci.yaml, .github/workflows/slash.yaml, .github/workflows/test_workflows.yml, .github/workflows/workflow_test.yml
=> More GitHub actions update

workflows/gen_crates.py
Changes the RO-Crate generating script to add *all* workflows (and related test suites) to the crate as listed in the Dockstore file. One will be arbitrarily picked to be the `mainEntity` of the crate (the one that will be recognized by WorkflowHub).
=> gen_crates: add workflows as listed in the Dockstore file

workflows/epigenetics/atacseq/CHANGELOG.md, workflows/epigenetics/atacseq/atacseq.ga
I am sorry. I forgot a step in 0.5.0...
=> fix bug in ATAC-seq workflow

workflows/epigenetics/atacseq/CHANGELOG.md, workflows/epigenetics/atacseq/README.md, workflows/epigenetics/atacseq/atacseq-tests.yml, workflows/epigenetics/atacseq/atacseq.ga, workflows/epigenetics/cutandrun/CHANGELOG.md, workflows/epigenetics/cutandrun/README.md, workflows/epigenetics/cutandrun/cutandrun-tests.yml, workflows/epigenetics/cutandrun/cutandrun.ga
Hopefully @MayranA just found an error into the workflow which was present since 2021...
=> Fix rm dup in ATAC and CUT&RUN

.github/workflows/workflow_test.yml
just copy and paste from IUC .. not entirely sure if it will work out of the box
=> Add reporting of deployment errors

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/README.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8-tests.yml, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga
Expose some parameters and update labels and tags for better readability.
=> Vgp8 updateUpdate of Workflow 8 scaffolding with HiC

workflows/scRNAseq/baredsc/CHANGELOG.md, workflows/scRNAseq/baredsc/README.md, workflows/scRNAseq/baredsc/baredSC-1d-logNorm.ga, workflows/scRNAseq/baredsc/baredSC-2d-logNorm-tests.yml, workflows/scRNAseq/baredsc/baredSC-2d-logNorm.ga
I added a new parameter and used last version of baredSC.
This is on top of #309
=> Update bared sc WF

.github/workflows/ci.yaml, .github/workflows/workflow_test.yml, workflows/proteomics/openms-metaprosip/metaprosip.ga
=> bump workflows to 24.0

workflows/amplicon/qiime2/qiime2-I-import/.dockstore.yml, workflows/amplicon/qiime2/qiime2-I-import/CHANGELOG.md, workflows/amplicon/qiime2/qiime2-I-import/QIIME2-Ia-multiplexed-data-single-end.ga, workflows/amplicon/qiime2/qiime2-I-import/QIIME2-Ib-multiplexed-data-paired-end-tests.yml, workflows/amplicon/qiime2/qiime2-I-import/QIIME2-Ib-multiplexed-data-paired-end.ga, workflows/amplicon/qiime2/qiime2-I-import/QIIME2-Ic-demultiplexed-data-single-end.ga, workflows/amplicon/qiime2/qiime2-I-import/QIIME2-Id-demultiplexed-data-paired-end.ga, workflows/amplicon/qiime2/qiime2-II-denoising/.dockstore.yml, workflows/amplicon/qiime2/qiime2-II-denoising/CHANGELOG.md, workflows/amplicon/qiime2/qiime2-II-denoising/QIIME2-IIa-denoising-and-feature-table-creation-single-end.ga, workflows/amplicon/qiime2/qiime2-II-denoising/QIIME2-IIb-denoising-and-feature-table-creation-paired-end.ga
=> qiime2: remove spaces from names in dockstore.yml

workflows/scRNAseq/baredsc/baredSC-2d-logNorm.ga
The autoupdate had forgotten to update the workflow 2d.
I don't change the CHANGELOG has it was changed in #433
=> fix baredSC deployment

workflows/README.md
Hi there,
I added a part about multi-workflow directories (@bernt-matthias if you can have a look, would be great).
I added a part about the autoupdate and I think we need to change the strategy but I think it is good that it is described here.
=> Improve README on workflows

workflows/README.md
Fix problems introduced with #455 #447.
=> Fix README

workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/Assembly-decontamination-VGP9-tests.yml, workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/Assembly-decontamination-VGP9.ga, workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/CHANGELOG.md, workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/test-data/full contaminant + mito scaffold list.txt
The bug was a missing regex that caused the file with the list of contaminants to get erased and the contaminants were not removed. 
I fixed the problem and updated the tests to check for it. 
I also added a tool report listing the contaminants a mitochondrial scaffolds
=> VGP9 - Bug fixed and changing tests

workflows/genome-assembly/bacterial-genome-assembly/CHANGELOG.md, workflows/genome-assembly/bacterial-genome-assembly/bacterial_genome_assembly.ga
Updated the tool versions manually in the ToolDistillator parameters
Thanks 😃
=> Updating workflows/genome-assembly/bacterial-genome-assembly from 1.1.1 to 1.1.2

.github/workflows/ci.yaml, .github/workflows/enable_ci_workflows.yml, .github/workflows/setup.yml, .github/workflows/slash.yaml, .github/workflows/test_workflows.yml, .github/workflows/usegalaxy-star-installation.yml, .github/workflows/workflow_test.yml
Upgrade all used actions to the last major version.
=> Upgrade actions

.github/workflows/ci.yaml, .github/workflows/workflow_test.yml
With the release of planemo we can now improve the linting.
=> use `--iwc` in linting

website/pages/workflow/[id].vue
Fixes #570
It looks like I forgot to remove a second `h-screen`. That seem to be all of them though.
=> Fix run button not fully visible

website/components/IWCHeader.vue
I assume it was meant like this
=> Clarify masthead links

workflows/scRNAseq/pseudobulk-worflow-decoupler-edger/README.md
Adds credits on the Pseudo-bulk scRNA-seq pipeline, and mentions main differences for user's awareness.
=> Credits Persist-seq original pipeline for the Pseudo-bulk scRNA-seq pipeline

workflows/epigenetics/atacseq/CHANGELOG.md, workflows/epigenetics/atacseq/atacseq-tests.yml, workflows/epigenetics/atacseq/atacseq.ga
I am really sorry for this, I don't understand how it happened...
=> Fix bowtie2 options in ATAC

.gitignore
These are the mermaid diagrams generated during the site build process.
Alternatively, we could just include them and automatically update them on PR or periodically?  One pro would be getting mermaid diagrams natively rendered on github.  Potential cons would be we want folks to be viewing these on iwc.galaxyproject.org instead, and adds artifacts and noise to the repo that require keeping up to date?
FOR REVIEWERS:
=> Add *_diagrams.md to .gitignore. 

workflows/amplicon-mgnify/taxonomic-rank-abundance-summary-table/.dockstore.yml
@RZ9082 this is a PR with just your dockstore file.
=> Generate a dockstore for a directory with ga and tests

website/app.vue, website/layouts/default.vue, website/pages/index.vue
=> [website] Refactor layout overflow handling / fix scroll on workflow pages.

workflows/transcriptomics/rnaseq-de/README.md, workflows/transcriptomics/rnaseq-de/rnaseq-de-filtering-plotting.ga
=> Improve rnaseq-de workflow name and annotation

workflows/transcriptomics/goseq/README.md, workflows/transcriptomics/goseq/goseq-go-kegg-enrichment-analsis.ga
=> Improve goseq workflow name and annotation

workflows/epigenetics/atacseq/README.md, workflows/epigenetics/atacseq/atacseq.ga, workflows/epigenetics/average-bigwig-between-replicates/README.md, workflows/epigenetics/average-bigwig-between-replicates/average-bigwig-between-replicates.ga, workflows/epigenetics/chipseq-pe/README.md, workflows/epigenetics/chipseq-pe/chipseq-pe.ga, workflows/epigenetics/chipseq-sr/README.md, workflows/epigenetics/chipseq-sr/chipseq-sr.ga, workflows/epigenetics/consensus-peaks/README.md, workflows/epigenetics/consensus-peaks/consensus-peaks-atac-cutandrun-tests.yml, workflows/epigenetics/consensus-peaks/consensus-peaks-atac-cutandrun.ga, workflows/epigenetics/consensus-peaks/consensus-peaks-chip-pe-tests.yml, workflows/epigenetics/consensus-peaks/consensus-peaks-chip-pe.ga, workflows/epigenetics/consensus-peaks/consensus-peaks-chip-sr-tests.yml, workflows/epigenetics/consensus-peaks/consensus-peaks-chip-sr.ga, workflows/epigenetics/cutandrun/README.md, workflows/epigenetics/cutandrun/cutandrun.ga, workflows/epigenetics/hic-hicup-cooler/README.md, workflows/epigenetics/hic-hicup-cooler/chic-fastq-to-cool-hicup-cooler.ga, workflows/epigenetics/hic-hicup-cooler/hic-fastq-to-cool-hicup-cooler.ga, workflows/epigenetics/hic-hicup-cooler/hic-fastq-to-pairs-hicup.ga, workflows/epigenetics/hic-hicup-cooler/hic-juicermediumtabix-to-cool-cooler.ga
=> Tweak workflow names and description in epigenetics folder

website/pages/index.vue
=> Workflow highlight tweaks

website/components/WorkflowCard.vue, website/nuxt.config.ts, website/package-lock.json, website/package.json
=> Fix truncation of compact card view.

workflows/scRNAseq/baredsc/README.md, workflows/scRNAseq/baredsc/baredSC-1d-logNorm.ga, workflows/scRNAseq/baredsc/baredSC-2d-logNorm.ga, workflows/scRNAseq/fastq-to-matrix-10x/CHANGELOG.md, workflows/scRNAseq/fastq-to-matrix-10x/README.md, workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-cellplex-tests.yml, workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-cellplex.ga, workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-v3-tests.yml, workflows/scRNAseq/fastq-to-matrix-10x/scrna-seq-fastq-to-matrix-10x-v3.ga, workflows/scRNAseq/pseudobulk-worflow-decoupler-edger/README.md, workflows/scRNAseq/pseudobulk-worflow-decoupler-edger/pseudo-bulk_edgeR.ga, workflows/scRNAseq/scanpy-clustering/Preprocessing-and-Clustering-of-single-cell-RNA-seq-data-with-Scanpy.ga, workflows/scRNAseq/scanpy-clustering/README.md, workflows/scRNAseq/velocyto/README.md, workflows/scRNAseq/velocyto/Velocyto-on10X-filtered-barcodes.ga, workflows/scRNAseq/velocyto/Velocyto-on10X-from-bundled.ga
=> Improve annotation and names for single cell workflow

workflows/epigenetics/chipseq-pe/CHANGELOG.md, workflows/epigenetics/chipseq-pe/chipseq-pe.ga
=> Updating workflows/epigenetics/chipseq-pe from 0.13 to 0.14 (recreate the PR)

workflows/epigenetics/chipseq-sr/CHANGELOG.md, workflows/epigenetics/chipseq-sr/chipseq-sr.ga
=> Updating workflows/epigenetics/chipseq-sr from 0.13 to 0.14 (reopen PR)

website/app.vue, website/components/Filters.vue, website/components/WorkflowCard.vue, website/nuxt.config.ts, website/package-lock.json, website/package.json, website/pages/index.vue, website/stores/workflows.ts, website/tailwind.config.ts
Closes most of https://github.com/galaxyproject/iwc/issues/760.
Addressing doi's from dockstore in a separate PR, popping that issue out.
New filter style: 
FOR REVIEWERS:
=> More polish of the IWC landing page

scripts/workflow_manifest.py, website/models/workflow.ts, website/pages/workflow/[id].vue
DOI Missing: #workflow/github.com/iwc-workflows/functional-annotation-protein-sequences/main
DOI Missing: #workflow/github.com/iwc-workflows/annotation-helixer/main
DOI Missing: #workflow/github.com/iwc-workflows/parallel-accession-download/main
DOI Missing: #workflow/github.com/iwc-workflows/sra-manifest-to-concatenated-fastqs/main
DOI Missing: #workflow/github.com/iwc-workflows/rnaseq-de/main
DOI Missing: #workflow/github.com/iwc-workflows/brew3r/main
DOI Missing: #workflow/github.com/iwc-workflows/goseq/main
DOI Missing: #workflow/github.com/iwc-workflows/polish-with-long-reads/main
DOI Missing: #workflow/github.com/iwc-workflows/bacterial-genome-assembly/main
DOI Missing: #workflow/github.com/iwc-workflows/assembly-with-flye/main
DOI Missing: …
=> Add DOIs to presentation (when available).

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga
=> VGP8 - change merging tool and use fixed version of BWA-MEM2

workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/CHANGELOG.md, workflows/VGP-assembly-v2/hi-c-contact-map-for-assembly-manual-curation/hi-c-map-for-assembly-manual-curation.ga
=> VGP pre-curation - replace merging tool Picard with samtools

website/components/WorkflowCard.vue, website/models/workflow.ts, website/pages/workflow/[id].vue, website/stores/workflows.ts
~Builds on https://github.com/galaxyproject/iwc/pull/784~  Rebased.
This adds prettier URLs for all workflows, that I'm internally calling 'iwcIDs'.
FOR REVIEWERS:
=> Use iwc-id prettier URLs

website/tests/e2e/basic.spec.js
This changed with the merge of the metadata PR, which was parallel to the initial test implementation here.
=> Fix expected test title

workflows/VGP-assembly-v2/kmer-profiling-hifi-trio-VGP2/CHANGELOG.md, workflows/VGP-assembly-v2/kmer-profiling-hifi-trio-VGP2/kmer-profiling-hifi-trio-VGP2.ga
=> VGP 2 - add workflow report

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/README.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8-tests.yml, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga
=> VGP8 - Add Compleasm

workflows/VGP-assembly-v2/Assembly-Hifi-HiC-phasing-VGP4/Assembly-Hifi-HiC-phasing-VGP4-tests.yml, workflows/VGP-assembly-v2/Assembly-Hifi-HiC-phasing-VGP4/Assembly-Hifi-HiC-phasing-VGP4.ga, workflows/VGP-assembly-v2/Assembly-Hifi-HiC-phasing-VGP4/CHANGELOG.md, workflows/VGP-assembly-v2/Assembly-Hifi-HiC-phasing-VGP4/README.md
=> Vgp 4 - Add Compleasm 

workflows/VGP-assembly-v2/Purge-duplicate-contigs-VGP6/CHANGELOG.md, workflows/VGP-assembly-v2/Purge-duplicate-contigs-VGP6/Purge-duplicate-contigs-VGP6-tests.yml, workflows/VGP-assembly-v2/Purge-duplicate-contigs-VGP6/Purge-duplicate-contigs-VGP6.ga, workflows/VGP-assembly-v2/Purge-duplicate-contigs-VGP6/README.md
=> VGP 6 - add compleasm

workflows/metabolomics/gcms-metams/CHANGELOG.md, workflows/metabolomics/gcms-metams/Mass-spectrometry__GCMS-with-metaMS-tests.yml, workflows/metabolomics/gcms-metams/Mass-spectrometry__GCMS-with-metaMS.ga
https://github.com/galaxyproject/iwc/pull/824
=> gcms-metams from 0.1 to 0.2

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/README.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8-tests.yml, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga
=> VGP 8 - add format constraint on gfa input and samtools stats

.github/workflows/ci.yaml, .github/workflows/workflow_test.yml
For:
> We also wanted to add tests against iuc and iwc before the usegalaxy.org update. 
_Originally posted by @mvdbeek in [#20192](https://github.com/galaxyproject/galaxy/issues/20192#issuecomment-2889752151)_
Going off of what was done for 24.2: https://github.com/galaxyproject/iwc/commit/cb98fcfd0eaff04dfe8681d878967936ed2897ed
__________
FOR REVIEWERS:
=> Test against release_25.0

website/components/MarkdownRenderer.vue
For the workflow display this adds view control icons at top right; zoomable, pannable, etc.  Gestures also work.
FOR REVIEWERS:
=> Zoomable workflow diagrams

workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/CHANGELOG.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/README.md, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8-tests.yml, workflows/VGP-assembly-v2/Scaffolding-HiC-VGP8/Scaffolding-HiC-VGP8.ga
Plus automatic updates
FOR REVIEWERS:
=> VGP 8 - Add output with the merged assembly stats and MAPQ filtering

website/components/MarkdownRenderer.vue
Wip, tinkering with the zoom to make it feel better on both trackpad and mouse.
=> Diagram zoom fixes

website/public/category-descriptions/metabolomics.md
New category currently without a description:
Feel free to totally change this description.
=> Add metabolomics category description with mass spectrometry workflows

workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/Assembly-decontamination-VGP9-tests.yml, workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/Assembly-decontamination-VGP9.ga, workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/CHANGELOG.md, workflows/VGP-assembly-v2/Assembly-decontamination-VGP9/README.md
=> VGP 9 Major update - Replace kraken with FCS gx for assembly decontamination
